### ISSUE TITLE
Release v1.0.0 was removed from PyPI.org

### ISSUE THREAD

**Issue by robbwagoner** [explosion/srsly#19]
The [release package for 1.0.0 was removed from PyPI.org](https://pypi.org/project/srsly/#history). Doing this causes problems for many automated build systems and pipelines. Removing packages from repos is frowned upon. Please replace the package in PyPI. It it is broken in some way, please release a v1.0.1 instead of removing 1.0.0.

----
```
pip3 install srsly==1.0.0
Collecting srsly==1.0.0
  Could not find a version that satisfies the requirement srsly==1.0.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.1.0, 0.2.0, 2.0.0.dev0, 2.0.0.dev1, 2.0.0)
No matching distribution found for srsly==1.0.0
```
----
<img width="985" alt="Releases_·_explosion_srsly" src="https://user-images.githubusercontent.com/989361/71820992-1ec48780-304e-11ea-913b-0770f7dd62f6.png">

<img width="1148" alt="srsly_·_PyPI" src="https://user-images.githubusercontent.com/989361/71820812-9219c980-304d-11ea-90fc-5447b7caf0f6.png">

**Comment by honnibal** [comment]
We had a problem with the release artifacts we uploaded for that 1.0 release: the sdist didn't build correctly, and we didn't have 3.5 support. This caused some broken builds, so we unpublished it.

We should have a corrected version up shortly. Sorry for the inconvenience.

**Comment by robbwagoner** [comment]
@honnibal Understood. For future reference, if a release is broken, making a new release as hotfix/patch is the proper solution. I.e. a 1.0.1 should have been made to publish a correction to the broken 1.0.0.
