### ISSUE TITLE
New UltraJSON release soon

### ISSUE THREAD

**Issue by hugovk** [explosion/srsly#22]
Hello, after a few years, we'll be making a new release of upstream UltraJSON (aka ujson) soon:

https://github.com/ultrajson/ultrajson/issues/352

If there's anything included in this fork that would be useful upstream, please could you make PRs at:

https://github.com/ultrajson/ultrajson/

(The new home of https://github.com/esnme/ultrajson/)

Thank you!

**Comment by honnibal** [comment]
Thanks for letting us know, and thanks for all your work on the project!

I think we only took PRs from the tracker. I can report that the PRs we merged have been working well for us and our users (the library is in use by our project spaCy, so it's actually reasonably well tested).

If you need help getting wheels built, let us know. We have a tool to automate it: https://github.com/explosion/wheelwright . I think ujson should be able to use Wheelwright with little trouble.
