### ISSUE TITLE
How do I say “srsly”?

### ISSUE THREAD

**Issue by kinghuang** [explosion/srsly#54]
It takes too long to verbally spell out s-r-s-l-y! How is it meant to be spoken?

* seriously
* serially
* sirs-ly
* …?

**Comment by honnibal** [comment]
![srsly](https://user-images.githubusercontent.com/8059750/115477762-fe8efb00-a287-11eb-9084-9ef15668a36c.jpeg)

😇

It's "seriously". It's inspired by the owl memes, was available, and felt memorably related to serialisation. Also there was a bit of frustration with the serialisation packaging situation it addressed, so there was a hint of pique in the naming choice :). I do get the problem though, we probably should've explained!

**Comment by kinghuang** [comment]
Awesome. Thanks for settling that question for my team! 😄
