### ISSUE TITLE
Not support ensure_ascii=False for write_json

### ISSUE THREAD

**Issue by rocke-dong** [explosion/srsly#63]
Dear,

In json dump, there is a very useful feature ensure_ascii for non-English.
Actually, as a Chinese, I alwayse choose ensure_ascii=False.

Could srsly support ensure_ascii feature in write_json?
thanks!!

**Comment by adrianeboyd** [comment]
It's intentional that `srsly` doesn't support `ensure_ascii=False` to avoid any potential encoding problems that might result.

I totally understand how it's frustrating that the output is not human-readable, but we'd rather be sure that the data can be read back in without problems.
